### ISSUE TITLE
Initial implementation of the authorization screen

### ISSUE THREAD

**Issue by angelaraya** [janeirodigital/sai-impl-web#26]
Initial design based from https://solid.github.io/data-interoperability-panel/primer/authorization-agent.html#gathering-authorizations

**Comment by elf-pavlik** [comment]
Can we start with [`All` scope](https://solid.github.io/data-interoperability-panel/specification/#access-scopes) so that we can connect everything together?
After that, we could be adding more granular scopes, one per PR.

**Comment by elf-pavlik** [comment]
Initial work in #47

**Comment by elf-pavlik** [comment]
Authorize button shouldn't appear until the whole authorization information is displayed

**Comment by angelaraya** [comment]
While not completed, some work has been merged with #58. I'll close this in favor or more granular issues.
