### ISSUE TITLE
Provide a sample pod that can be used to test/develop with

### ISSUE THREAD

**Issue by angelaraya** [janeirodigital/sai-impl-web#3]
Developers can benefit from having a sample pod that conforms to the patterns and can be used to develop/test the libraries.

**Comment by elf-pavlik** [comment]
I started putting some snippets together already, those can be published separate git repository which in turn can be used with CSS.

**Comment by elf-pavlik** [comment]
Initial setup available in https://github.com/janeirodigital/sai-impl-service/tree/main/packages/css-storage-fixture

We can keep improving it via PRs
