### ISSUE TITLE
Design Language Picker

### ISSUE THREAD

**Issue by angelaraya** [janeirodigital/sai-impl-web#36]
Users should be able to pick their language of preference at any point where a text is shown in the screen. Preferably through a footer/navbar picker.

**Comment by angelaraya** [comment]
Related to #35

**Comment by elf-pavlik** [comment]
> Preferably through a footer/navbar picker.

I would consider having an option to set the preferred language in one place and not show the language picker all the time.

As a low priority, we should consider a case where descriptions are available in multiple languages but not one selected by the user, in that case, they should be able to choose a language available for those specific descriptions.

We discussed in slack that angular allows compiling time i18n which seems reasonable for the UI. We would probably separate handing i18n for UI, and for dynamic data, pretty much access needs and shape trees descriptions.

**Comment by angelaraya** [comment]
Completed #57
