### ISSUE TITLE
encode any url used in query params

### ISSUE THREAD

**Issue by elf-pavlik** [janeirodigital/sai-impl-web#65]
whenever we use a url in query params it should be urlencoded

**Comment by angelaraya** [comment]
Can you point me to where are you seen this? I'll happily fix it.

**Comment by elf-pavlik** [comment]
Not sure if angular does it automatically in https://github.com/janeirodigital/sai-impl-web/blob/08504c949f744f38777df4af3dc19addf5bcd175/src/app/components/authorization/authorization.component.html#L46

We noticed in the demo app (projectron) that thinks were failing due to # in the query param value

**Comment by angelaraya** [comment]
![image](https://user-images.githubusercontent.com/57408730/214105233-b282e87f-9afd-4ee6-bcb5-c399faf1e4c4.png)
I could not find any concrete reference in the documentation to whether it encodes it or not, but from what I can see and test it does.

If you can reproduce then I can look more into it.
